// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdeg9QYxdwHaVB9jtxwwL6ZZ5IKSOOAY',
    appId: '1:427523182162:web:cdcf8a0d7f94d8045e598b',
    messagingSenderId: '427523182162',
    projectId: 'workout-app-74a14',
    authDomain: 'workout-app-74a14.firebaseapp.com',
    storageBucket: 'workout-app-74a14.appspot.com',
    measurementId: 'G-QXN0VM4ETF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCtnzkNTzce-Nd6rNTWJgh7zQgB3cJQc',
    appId: '1:427523182162:android:3f89e07b9754f0f95e598b',
    messagingSenderId: '427523182162',
    projectId: 'workout-app-74a14',
    storageBucket: 'workout-app-74a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GXt8q3xgRY1ynLcTA85XtxlvjgnoX-E',
    appId: '1:427523182162:ios:a85fde56b5e5ce2b5e598b',
    messagingSenderId: '427523182162',
    projectId: 'workout-app-74a14',
    storageBucket: 'workout-app-74a14.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_GXt8q3xgRY1ynLcTA85XtxlvjgnoX-E',
    appId: '1:427523182162:ios:a85fde56b5e5ce2b5e598b',
    messagingSenderId: '427523182162',
    projectId: 'workout-app-74a14',
    storageBucket: 'workout-app-74a14.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAdeg9QYxdwHaVB9jtxwwL6ZZ5IKSOOAY',
    appId: '1:427523182162:web:f52802d31e0fbaef5e598b',
    messagingSenderId: '427523182162',
    projectId: 'workout-app-74a14',
    authDomain: 'workout-app-74a14.firebaseapp.com',
    storageBucket: 'workout-app-74a14.appspot.com',
    measurementId: 'G-QJ0XCPY2LY',
  );
}
